### ISSUE TITLE
Create a front end service to upload a picture and get tagged picture in return

### ISSUE THREAD

**Issue by ankursam** [himanshutyagi36/IBMCallForCode#2]

**Comment by himanshutyagi36** [comment]
**Tasks**
- [x] node code to upload a file
- [x] code for connecting to cloudant
- [x] Upload and store image in cloudant
- [x] node code for downloading the image
- ~[ ] (if time allows) show the image embedded in the UI~

**Comment by himanshutyagi36** [comment]
For downloads, we can have the following strategy
- Once the backend python application is done with the training, it can send a `POST` request to this nodejs application, with the names of the newly created images.Then we can go ahead and download the image(s) to the filesystem.
@ankursam
